title: Shipyard
description: A sweet front-end framework for Ruby on Rails and Jekyll.
baseurl: /
url: https://codeship.github.io
permalink: /:title
sass:
  style: compressed

# Build settings
encoding: utf-8
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html
    block:
      css: class
      wrap: true
      disable: false
      css_class: 'code-block'
    span:
      css: class
      wrap: true
      disable: false
      css_class: 'code-inline'

plugins:
  - jekyll-assets

assets:
  autowrite: true
  assets:
    - "*.svg"
  sources:
    - _assets/js
    - _assets/css
    - _assets/img

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "application"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
