shipyard:
  image: jekyll/jekyll:3.8.5
  environment:
    - JEKYLL_VERSION=3.8.5
    - BUNDLE_ARGS='--without=ci_group'
  command: jekyll serve --watch --incremental --livereload
  ports:
    - 4000:4000
  volumes:
    - $PWD:/srv/jekyll
    - $PWD/vendor/bundle:/usr/local/bundle
