FROM starefossen/ruby-node:2-10-slim

RUN apt-get update
RUN apt-get install -y build-essential jq git

RUN mkdir /usr/src/app
WORKDIR /usr/src/app
COPY . .

RUN bundle install
RUN echo "$(git ls-remote --get-url)"
RUN git clone git@github.com:cloudbees/shipyard.git --branch gh-pages _site
RUN bundle exec jekyll build --baseurl="/shipyard"
